### ISSUE TITLE
Marmiton import failed

### ISSUE THREAD

**Issue by dompe-9** [vabene1111/recipes#208]
Version: 0.11.0 on unraid

When I want to import any recipe from marmiton.org, I have always this error

![Capture](https://user-images.githubusercontent.com/47984051/97473675-8e905f80-194b-11eb-8f12-813261b97818.PNG)

**Comment by vabene1111** [comment]
i will take a look at this, thanks for reporting

**Comment by sebimarkgraf** [comment]
I just tried around 10 recipes from marmiton.org and could not find the issue on 0.11.1

@dompe-9 could you provide a link to one recipe that is not working for you? 
Maybe they changed something or the update to microdata fixed the problem

**Comment by dompe-9** [comment]
I try this recipe on 0.11.1 and it doesn't works : 
https://www.marmiton.org/recettes/recette_cookies-coeur-caramel_347052.aspx

**Comment by sebimarkgraf** [comment]
That one worked for me. 

Which sort of setup did you choose?

Do imports from other sites work for you?

**Comment by dompe-9** [comment]
Yes I can import from other sites, it's the only that doesn't works.

I'm on Unraid 6.9.0-beta30 and i use the docker vabene1111/recipes

**Comment by dompe-9** [comment]
I fully reinstall the docker and still the same issue

**Comment by vabene1111** [comment]
what exact error do you get ?

**Comment by dompe-9** [comment]
The same one 
https://user-images.githubusercontent.com/47984051/97473675-8e905f80-194b-11eb-8f12-813261b97818.PNG

**Comment by vabene1111** [comment]
very interesting

can you send me the container logs ? i dont know how that works in unraid but normally that would be `docker-compose logs -f`
best would be from the moment you make the request.

the 500 error indicates that something completly broke the parser which makes it even more mysterious that this specific recipe works for other people

**Comment by dompe-9** [comment]
Is that ok ?

`[2020-12-13 22:35:50 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2020-12-13 22:35:50 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2020-12-13 22:35:50 +0000] [1] [INFO] Using worker: sync
[2020-12-13 22:35:50 +0000] [12] [INFO] Booting worker with pid: 12
192.168.0.26 - - [13/Dec/2020:22:35:51 +0000] "GET / HTTP/1.1" 302 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
192.168.0.26 - - [13/Dec/2020:22:35:51 +0000] "GET /search/ HTTP/1.1" 200 9370 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
192.168.0.26 - - [13/Dec/2020:22:35:51 +0000] "GET /static/themes/select2-bootstrap-theme.d007f71f4d38.css HTTP/1.1" 200 0 "http://192.168.0.30:8154/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"

0.26 - - [13/Dec/2020:22:35:51 +0000] "GET /static/css/select2-bootstrap.dcec0cc93fba.css HTTP/1.1" 200 0 "http://192.168.0.30:8154/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
192.168.0.26 - - [13/Dec/2020:22:35:51 +0000] "GET /static/css/select2.min.9f54e6414f87.css HTTP/1.1" 200 0 "http://192.168.0.30:8154/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
192.168.0.26 - - [13/Dec/2020:22:35:51 +0000] "GET /static/themes/flatly.min.f99bb7c874e0.css HTTP/1.1" 200 0 "http://192.168.0.30:8154/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
192.168.0.26 - - [13/Dec/2020:22:35:51 +0000] "GET /static/fontawesome/fontawesome_all.min.2acd020d0b21.css HTTP/1.1" 200 0 "http://192.168.0.30:8154/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
192.168.0.26 - - [13/Dec/2020:22:35:51 +0000] "GET /static/js/jquery-3.5.1.min.dc5e7f18c8d3.js HTTP/1.1" 200 0 "http://192.168.0.30:8154/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
192.168.0.26 - - [13/Dec/2020:22:35:51 +0000] "GET /static/js/popper.min.84415b7368fd.js HTTP/1.1" 200 0 "http://192.168.0.30:8154/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
192.168.0.26 - - [13/Dec/2020:22:35:51 +0000] "GET /static/js/bootstrap.min.61f338f870fc.js HTTP/1.1" 200 0 "http://192.168.0.30:8154/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
192.168.0.26 - - [13/Dec/2020:22:35:51 +0000] "GET /static/js/select2.min.0f64f3a3a0c6.js HTTP/1.1" 200 0 "http://192.168.0.30:8154/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
192.168.0.26 - - [13/Dec/2020:22:35:51 +0000] "GET /static/webfonts/fa-solid-900.44d537ab79f9.woff2 HTTP/1.1" 200 0 "http://192.168.0.30:8154/static/fontawesome/fontawesome_all.min.2acd020d0b21.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
192.168.0.26 - - [13/Dec/2020:22:36:07 +0000] "GET /accounts/login/ HTTP/1.1" 200 7726 "http://192.168.0.30:8154/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
192.168.0.26 - - [13/Dec/2020:22:36:39 +0000] "POST /accounts/login/ HTTP/1.1" 200 7896 "http://192.168.0.30:8154/accounts/login/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
192.168.0.26 - - [13/Dec/2020:22:36:57 +0000] "POST /accounts/login/ HTTP/1.1" 302 0 "http://192.168.0.30:8154/accounts/login/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
192.168.0.26 - - [13/Dec/2020:22:36:57 +0000] "GET / HTTP/1.1" 302 0 "http://192.168.0.30:8154/accounts/login/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
192.168.0.26 - - [13/Dec/2020:22:36:57 +0000] "GET /search/ HTTP/1.1" 200 17074 "http://192.168.0.30:8154/accounts/login/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
192.168.0.26 - - [13/Dec/2020:22:36:57 +0000] "GET /static/custom/js/form_multiselect.8dc17c88ebd1.js HTTP/1.1" 200 0 "http://192.168.0.30:8154/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
192.168.0.26 - - [13/Dec/2020:22:37:08 +0000] "GET /data/import/url HTTP/1.1" 200 29076 "http://192.168.0.30:8154/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
192.168.0.26 - - [13/Dec/2020:22:37:08 +0000] "GET /static/css/bootstrap-vue.min.31eedf134085.css HTTP/1.1" 200 0 "http://192.168.0.30:8154/data/import/url" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
192.168.0.26 - - [13/Dec/2020:22:37:08 +0000] "GET /static/css/vue-multiselect.min.7e898f8cb587.css HTTP/1.1" 200 0 "http://192.168.0.30:8154/data/import/url" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
192.168.0.26 - - [13/Dec/2020:22:37:08 +0000] "GET /static/js/vue.min.6c81f02ad0bf.js HTTP/1.1" 200 0 "http://192.168.0.30:8154/data/import/url" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
192.168.0.26 - - [13/Dec/2020:22:37:08 +0000] "GET /static/js/vue-resource.f35ad4319486.js HTTP/1.1" 200 0 "http://192.168.0.30:8154/data/import/url" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
192.168.0.26 - - [13/Dec/2020:22:37:08 +0000] "GET /static/js/js.cookie.min.92cac509bce9.js HTTP/1.1" 200 0 "http://192.168.0.30:8154/data/import/url" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
192.168.0.26 - - [13/Dec/2020:22:37:08 +0000] "GET /static/js/bootstrap-vue.min.484d959dc285.js HTTP/1.1" 200 0 "http://192.168.0.30:8154/data/import/url" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
192.168.0.26 - - [13/Dec/2020:22:37:08 +0000] "GET /static/js/vue-multiselect.min.4454b471434f.js HTTP/1.1" 200 0 "http://192.168.0.30:8154/data/import/url" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
/opt/recipes/venv/lib/python3.8/site-packages/django/views/generic/list.py:86: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'cookbook.models.Keyword'> QuerySet.
return self.paginator_class(
192.168.0.26 - - [13/Dec/2020:22:37:08 +0000] "GET /dal/keyword/?q= HTTP/1.1" 200 46 "http://192.168.0.30:8154/data/import/url" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
/opt/recipes/venv/lib/python3.8/site-packages/django/views/generic/list.py:86: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'cookbook.models.Unit'> QuerySet.
return self.paginator_class(
192.168.0.26 - - [13/Dec/2020:22:37:08 +0000] "GET /dal/unit/?q= HTTP/1.1" 200 46 "http://192.168.0.30:8154/data/import/url" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
/opt/recipes/venv/lib/python3.8/site-packages/django/views/generic/list.py:86: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'cookbook.models.Food'> QuerySet.
return self.paginator_class(
192.168.0.26 - - [13/Dec/2020:22:37:08 +0000] "GET /dal/food/?q= HTTP/1.1" 200 46 "http://192.168.0.30:8154/data/import/url" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
192.168.0.26 - - [13/Dec/2020:22:37:16 +0000] "POST /api/recipe-from-url/ HTTP/1.1" 200 3027 "http://192.168.0.30:8154/data/import/url" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
1.5 kg de rôti de boeuf (rosbif) roulé
500 g de champignon de Paris
200 g de fromage frais ail et fines herbes (type boursin)
6 cuillères à soupe de pesto rouge
40 cl de bouillon de boeuf
4 cuillères à soupe d'huile d'olive
/opt/recipes/venv/lib/python3.8/site-packages/PIL/Image.py:2894: UserWarning: image file could not be identified because WEBP support not installed
warnings.warn(message)
192.168.0.26 - - [13/Dec/2020:22:37:20 +0000] "POST /data/import/url HTTP/1.1" 500 145 "http://192.168.0.30:8154/data/import/url" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"`

**Comment by vabene1111** [comment]
very interesting, i had expected some more prominent error that that 😂 

are you running sqlite or postgresql ?

**Comment by dompe-9** [comment]
The container can use both but by default it's sqlite

**Comment by vabene1111** [comment]
and what is it that you use ?

just asking because i saw all the special characters maybe sqlite does not like some of them while postgres can handle it (should not be the case but worth investigating i guess)

**Comment by dompe-9** [comment]
Yes i use sqlite.
I will try to reinstall it with postgres for test

**Comment by vabene1111** [comment]
dont worry about that, i have just tested the recipe again both on my postgres and my sqlite setup both dont work.

**Comment by vabene1111** [comment]
I saw an internal ip in the logs above. Are your running your application at home on some kind of PC or in a datacenter ?

The request for the import is made by the server thus some web pages might decide to block incoming traffic from datacenter IP addresses ?

**Comment by dompe-9** [comment]
The application is running at home on my Unraid server.
192.168.0.26 is my laptop
192.168.0.30 is unraid server

**Comment by vabene1111** [comment]
ok so the network should not be a problem ... 

The recipe shown in the docker compose log above is not the same as mentioned above but fails anyway .. 

i mean there is the PIL image warning but i dont know why this should lead to a 500 without any debug information AND what is more important i cannot reproduce it ..

Do you by chance have some weird internet provider who could apply some kind of image compression/replacement techniques ? You could test that by running the request trough a VPN but that would mean you have to setup your unraid to do that, i donw know how easy that is .. or just run the DEV setup locally that should work too (would also maybe give you some more debug information)

**Comment by dompe-9** [comment]
My docker was not in debug mode.
I have more logs
[Recipes logs.txt](https://github.com/vabene1111/recipes/files/5689089/Recipes.logs.txt)

I will try with a VPN

**Comment by vabene1111** [comment]
ok from that log it definitely looks like the image is the problem. Now we need to find out what image you are getting since you seem to get a different one to mine and the other testers above. 

This might be related to some kind of Network compression thing or have some completely different reason ...

**Comment by dompe-9** [comment]
I try with a VPN, same problem

In the docker parameters, I have a Gunicorn media option, but enable/disable nothing change.

![recipes](https://user-images.githubusercontent.com/47984051/102097912-cb92b180-3e26-11eb-9fb1-00ce6cca00b9.PNG)

**Comment by vabene1111** [comment]
gunicorn media should not have anything to do with this. 

From what i can gather from the logs is that the server gives you a WEBP which is a special image format uses on some websites. The question is why you get this different kind of image while i (an @sebimarkgraf ) get normal images that can be parsed 
```
/opt/recipes/venv/lib/python3.8/site-packages/PIL/Image.py:2894: UserWarning: image file could not be identified because WEBP support not installed
```

or maybe we get the same image but for some reason our installations can handle it (which does not make much sense because its docker) 

This could probably be fixed by (as the error message says) installing WEBP support but i would like to first understand why this is happening to prevent future issues.

**Comment by dompe-9** [comment]
I ask on the Unraid forum if somebody can import from this website to recipes, and one person said he can...
I don't understand why it doesn't work for me. I don't think it's my ISP (Orange fiber, France) because nothing change with a VPN.

I will try with a new serveur for test.

How can I install WEBP to know if it's really the problem ?

**Comment by vabene1111** [comment]
thats a very good question ...

here is a post that might help https://stackoverflow.com/questions/55349110/webp-support-not-installed-error-with-pillow-included-in-anaconda

you could try to executre into the image but would suggest rebuilding it by changing the dockerfile and adding the apt packages 

are you fit with python/debugging stuff so we can try some more advanced ?

**Comment by vabene1111** [comment]
i was just going trough the issues to fix some stuff and noticed that the recipe mentioned here #215 produces the same error and is reproducible for me.

I honestly dont see what is wrong with the image and its easily fixable by just adding a try except blog around the image importing. If the image gets lost on import its also not a huge problem so i guess this is a good solution. 

if we ever find out whats wrong we cann still add it

**Comment by dompe-9** [comment]
Is 0.12.0 version have the fix for this ?

**Comment by vabene1111** [comment]
it should, yes.

**Comment by dompe-9** [comment]
Ok, problem still present

**Comment by vabene1111** [comment]
ok that is very interesting. I added an exception blog around the code that produces the error we found in your logs. Have you checked the system page that you are running the latest release ?

If so can you please send me another log

**Comment by dompe-9** [comment]
Yes, i'm in 0.12.0

Logs : 
`/opt/recipes/venv/lib/python3.8/site-packages/PIL/Image.py:2942: UserWarning: image file could not be identified because WEBP support not installed
warnings.warn(message)
Internal Server Error: /data/import/url

Traceback (most recent call last):
File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
response = get_response(request)
File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/recipes/venv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
return view_func(request, *args, **kwargs)
File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
return func(*args, **kwds)
File "/opt/recipes/cookbook/views/data.py", line 148, in import_url
img = Image.open(BytesIO(response.content))
File "/opt/recipes/venv/lib/python3.8/site-packages/PIL/Image.py", line 2943, in open
raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x15532c66d6d0>`

![Capture](https://user-images.githubusercontent.com/47984051/102364909-47236880-3fb7-11eb-91e1-4f6ca9ad697c.PNG)

**Comment by vabene1111** [comment]
ok i will take a look when i have time but might be a little before that is the case

**Comment by sephrat** [comment]
I have the exact same issue here. Running a docker install on Ubuntu with version 0.12.0. 


```
UnidentifiedImageError at /data/import/url

cannot identify image file <_io.BytesIO object at 0x7f33bede3e50>

Request Method: 	POST
Request URL: 	http://web:8080/data/import/url
Django Version: 	3.1.3
Exception Type: 	UnidentifiedImageError
Exception Value: 	

cannot identify image file <_io.BytesIO object at 0x7f33bede3e50>

Exception Location: 	/opt/recipes/venv/lib/python3.8/site-packages/PIL/Image.py, line 2943, in open
Python Executable: 	/opt/recipes/venv/bin/python
Python Version: 	3.8.6
Python Path: 	

['/opt/recipes',
 '/opt/recipes/venv/bin',
 '/usr/local/lib/python38.zip',
 '/usr/local/lib/python3.8',
 '/usr/local/lib/python3.8/lib-dynload',
 '/opt/recipes/venv/lib/python3.8/site-packages']
```
Stacktrace is the same as above.
I found this in the full stacktrace:
`image file could not be identified because WEBP support not installed`

I tried a bunch of Marmiton recipes, they all fail. I can import from other sites OK. I can import fine with Nextcloud's cookbook app if that's of any help (the image is fetched fine as well).

For the record I get `PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f33bef9a130>` when trying to import recipe from #215, but nothing about the WEBP thing from Marmiton.

**Comment by vabene1111** [comment]
This is very interesting. I put the whole block that produces the error in the log above into a try: except: blog to simply not import the image in case anything goes wrong there (in PR f72fc699f839cb8968bb29cb1e03b5af53941c16)

```python
 try:
      response = requests.get(data['image'])
      img = Image.open(BytesIO(response.content))

      # todo move image processing to dedicated function
      basewidth = 720
      wpercent = (basewidth / float(img.size[0]))
      hsize = int((float(img.size[1]) * float(wpercent)))
      img = img.resize((basewidth, hsize), Image.ANTIALIAS)

      im_io = BytesIO()
      img.save(im_io, 'PNG', quality=70)
      recipe.image = File(im_io, name=f'{uuid.uuid4()}_{recipe.pk}.png')
      recipe.save()
  except UnidentifiedImageError:
      pass
```
this is in the `data.py` file refrenced above in the stacktrace 
```
File "/opt/recipes/cookbook/views/data.py", line 148, in import_url
img = Image.open(BytesIO(response.content))
```
so i dont really understand why it still raises this error while it was explicitly suppressed. 

The Problem is that i still can reproduce the issue. Are you living in france as well @sephrat and have the same ISP by chance or are you running from a datacenter/anywhere else ?

**Comment by sephrat** [comment]
I can't find the code you quoted in my docker image, are you sure you made it to 0.12.0?
Also, any chance to get support for webp images (which seems to be the issue here)? Surely it's better to have no image than no recipe, but Marmiton is one of the (if not THE) largest recipes website in France. 

The app runs on my home server in France with a different ISP (SFR). Do you think it would have to do with their CDN settings or something? Not sure how I can help debugging this but I'm happy to help.

**Comment by vabene1111** [comment]
oh i am such an idiot ... i dont know how this happened because i tought i released all importer fixes with 0.12 but turns out this exect one was made after i released it 😕 

i will need to test some changes but a 0.12.1 can be expected the next few days .. sry for the confusion

**Comment by sephrat** [comment]
OK I found something really weird. I manually installed the app on my Windows 10 PC and I can import recipes from Marmiton just fine. So definitely not related to geographic region or whatever: both setups run on the same network.
Could it be specific to the docker image?

**Comment by vabene1111** [comment]
yes, from what i figured from the stackoverflow post it has to do with a specific package being installed when building the container or installing the packages via Pip.

Or did you use the pre build image ?

**Comment by sephrat** [comment]
I encounter this issue with the pre-built image vabene1111/recipes. Just to be sure I removed the container and started it up again, the issue persists. I use a config similar to https://github.com/vabene1111/recipes/tree/develop/docs/docker/plain. 
Also if it's worth anything, when I first tested this app a couple months ago (early september), I succeeded to import Marmiton recipes with roughly the same setup.

It works fine on Windows where I installed everything manually with pip.

**Comment by vabene1111** [comment]
very very interesting .. 

i have released v0.12.1 which should fix the issue. I will add some debug code to dump the exact request URL of the image and maybe event the raw ByteStream when the import failes with one of the next releases so we might actually find out whats wrong.

**Comment by dompe-9** [comment]
It works for me , i have to insert the image manually after but it's ok.
Thanks

**Comment by sephrat** [comment]
Yep, no more error 500.
Still feels weird though that the image is displayed in the form before importing, but not actually imported.

**Comment by Axolord** [comment]
I am on 0.12.1 but the problem still occurs. I actually found no website, that was not buggy.
Most of the time the scraping works alright, but when I try to save it I still get Error 500 via alert.

May it be because of a wrong config? The docker logs do not show anything interesting.

Thanks for the app and the support btw! Awesome project

**Comment by Axolord** [comment]
I turned on the debug mode and found the following exception:

```
web_recipes_1    | Internal Server Error: /data/import/url
web_recipes_1    | Traceback (most recent call last):
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
web_recipes_1    |     response = get_response(request)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
web_recipes_1    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
web_recipes_1    |     return view_func(request, *args, **kwargs)
web_recipes_1    |   File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
web_recipes_1    |     return func(*args, **kwds)
web_recipes_1    |   File "/opt/recipes/cookbook/views/data.py", line 146, in import_url
web_recipes_1    |     if data['image'] != '':
web_recipes_1    | KeyError: 'image'
web_recipes_1    | 192.168.128.3 - - [23/Dec/2020:22:40:36 +0000] "POST /data/import/url HTTP/1.0" 500 70644 "https://mywebsite" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
```

So it might also be connected to the problem with the image?

**Comment by vabene1111** [comment]
thanks for the additional info and the logs. This is actually a different error but one that might be related to the first one as well so it definitly helps to look into this as well ...

maybe my fix introduced a new bug that just looks like the old :thinking:

**Comment by vabene1111** [comment]
ok so this issue should be resolved as well with the next update and also directly on dev branch. If anyone encounters any new issues please open a new issue

**Comment by JamesDAdams** [comment]
Hi,

i use the dev branch and the import work exept for the pictures (for marmiton.org)

He found the picttures : 
![image](https://user-images.githubusercontent.com/20860324/105635168-e9115d00-5e61-11eb-9697-ec5facdc9986.png)


But after import, the images is missing.

![image](https://user-images.githubusercontent.com/20860324/105635174-f6c6e280-5e61-11eb-8412-5e9c72234f98.png)

**Comment by vabene1111** [comment]
yes that is basically the fix. It might be possible to display the image in the browser but for some reason the byte stream returned by when trying to import the image from the url is not parsable. 

I am sure there is a way to fix this but as i cannot even reproduce the issue this was the easiest way of doing so

**Comment by JamesDAdams** [comment]
ok :(

**Comment by callingshotgun** [comment]
So FYI, I recently ran into a similar issue (won't import images) with other recipe software (Mealie), that seemed to do it for the same sites.  Using the library that application used for scraping JSON and recipes, it became apparent that the problem was user-agents.  The image shows up fine in the "preview" because your browser requested the image file. user-agent:Mozila(blahblahblah).  But when the scraper is pulling down files a default useragent isn't being listed, which causes some HTTP 403 type errors.  Wrapping the image-grab in a try-catch block that tries again with a user-agent when the first try fails might fix the issue.

**Comment by vabene1111** [comment]
thats interesting, thanks for the info, i will check that out and see if i can fix the issue with that
