### ISSUE TITLE
Attempt to Import an Exported Recipe Failes

### ISSUE THREAD

**Issue by smilerz** [vabene1111/recipes#384]
### Version
Version: 0.13.0

### Bug description
Exported an existing recipe - changed the name and imported.  Traceback threw the following error:
`Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/recipes/venv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/recipes/cookbook/views/import_export.py", line 31, in import_recipe
    recipe = sr.save()
  File "/opt/recipes/venv/lib/python3.8/site-packages/drf_writable_nested/mixins.py", line 231, in save
    return super(BaseNestedModelSerializer, self).save(**kwargs)
  File "/opt/recipes/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/opt/recipes/cookbook/serializer.py", line 160, in create
    validated_data['created_by'] = self.context['request']._user

Exception Type: KeyError at /import/
Exception Value: 'request'`

**Comment by vabene1111** [comment]
yes, there were several issues, they should be fixed with the next release. Please let me know if that is not the case, sry for the inconvenience, the import/export module needs a complete rework

**Comment by smilerz** [comment]
@vabene1111 - thanks.  Are the fixes currently in the beta branch?  I'm running master, but can switch.

**Comment by vabene1111** [comment]
you can switch to the beta branch and it should have the fix but please note that it is NOT possible to downgrade, if you encounter any issues on beta you are stuck (but usually i dont take long fixing them)

**Comment by tdvantine** [comment]
This is still an issue on the newest release, different error though. when importing and leaving the `Type` set to Default, uploading a zip with an exported json produces the error message `Importer expected a .zip file. Did you choose the correct importer type for your data ?`

**Comment by vabene1111** [comment]
was the export produced in the new exporter version (anything from 0.14.0 onwards) ?

Because the old exports can no longer be imported in v0.14.x 

If yes are you uploading the exact zip you downloaded before ? If so would you mind sharing it with me, so i can verify what causes the issue ?

If needed i can give you a place to share it privatly if you want

**Comment by tdvantine** [comment]
It is from the beta docker branch. Go to recipe, ellipse menu, export, include image, download, downloads as a .json. So I zipped the json and imported into 0.14.5 and got the error.

**Comment by vabene1111** [comment]
sadly between the beta and the latest version the exporter was reworked completely.

If you need to get back to your recipes i would recommend spinning up the beta (which has not yet been updated further), import the recipes there. Then upgrade to the latest version, perform the new export and import it into your production database

**Comment by tdvantine** [comment]
Awesome, so your saying just take the `beta` tag off of the docker compose, export, then go to the new instance and import? Sounds simple enough. Better than copying 25 recipes. (I have tried `dumpdata` and `loaddata` as well as postgres export and import and none worked lol)

**Comment by vabene1111** [comment]
yea sadly djangos native dumpdata/loaddata commands dont really handle complex foreign key structures very well.

It is like you said, remove the tag, update to the latest version, export what you like (i definitly need to build an export all function, sry you need to do it manually) and import that file into the new database

**Comment by tdvantine** [comment]
Still get the same error, after adding `client_max_body_size 2M;` to nginx to allow upload. (Side note i will be rewriting the manual install and will probably include that in it). I switched to :develop as no tag gave me version 13. I can see the difference, but still expects a zip even when i give it a zip.

**Comment by vabene1111** [comment]
yea the error message is kind of a catch all .. if the import is from the same version to another same version i would need to take a look at it if i should help 

If you want feel free to send me the zip on discord vabene1111#5492 , i will see if i can reproduce the error and fix it for you
